### ISSUE TITLE
Use BrokenRecord.jl for the test suite?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaHealth/PubChemCrawler.jl#14]
Instead of actually hitting the live PubChem API during the test suite, you could instead use Chris's excellent package BrokenRecord.jl: https://github.com/JuliaTesting/BrokenRecord.jl

**Comment by timholy** [comment]
Great suggestion! It's nice having the tests run so fast, but especially to resolve the weirdnesses about PubChem's enforced timeouts.
