### ISSUE TITLE
Cool, a Great Julia extension~ but how can I convert some SMILES to their CAS ID?

### ISSUE THREAD

**Issue by Wang-Lin-boop** [JuliaHealth/PubChemCrawler.jl#17]

**Comment by timholy** [comment]
Get the `cid` and then see https://juliahealth.org/PubChemCrawler.jl/stable/#PubChemCrawler.get_for_cids.

**Comment by Wang-Lin-boop** [comment]
> Get the `cid` and then see https://juliahealth.org/PubChemCrawler.jl/stable/#PubChemCrawler.get_for_cids.

Oh, cool~ thank you, Let me try it.
