### ISSUE TITLE
When to go to 1.0?

### ISSUE THREAD

**Issue by timholy** [JuliaHealth/PubChemCrawler.jl#8]
This package now does what I want it to, so I might not extend it much more. But of course it's still rather new. That raises the question, what to call the next release? 0.1.1? Or 1.0?

**Comment by DilumAluthge** [comment]
Personally, I would say go to 1.0 now. If for some reason you need to make a breaking change, there's always 2.0, 3.0, etc.

**Comment by timholy** [comment]
I'm inclined to agree. I have one more big real-world workout for this package coming up in the next few days, and as long as nothing too horrible about its behavior emerges, I will likely go to 1.0.
